In [7]:
import numpy as np

In [9]:

a=np.array([1,2,3])
a=np.array([[1,2],[3,4]])
a=np.array([1,2,3,4,5],ndmin=2)
a=np.array([1,2,3],dtype=complex)
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [10]:
#dimensions
a.ndim


2

In [11]:
#Resizing an Array

a = np.array([[1,2,3],[4,5,6]])

a.shape = (3,2)

a = np.array([[1,2,3],[4,5,6]])

b = a.reshape(3,2)

a = np.arange(24)

x = np.arange(10,20,2)

b = a.reshape(2,4,3)

In [12]:
#Returns the length of each element of array in bytes.

x = np.array([1,2,3,4,5], dtype = np.int8)

print (x.itemsize)

x = np.array([1,2,3,4,5])

print (x.flags)


1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [ ]:
#Array Creation

#numpy.empty(shape, dtype = float, order = 'C')

#C' for C-style row-major array 'F' for FORTRAN
#style column-major array

x = np.empty([3,2], dtype = int)


In [14]:
#Array with Zero

x = np.zeros(5)

x = np.zeros((5,), dtype = int)


In [15]:
#Array with Ones

x = np.ones([2,2], dtype = int)

In [16]:
#Array from Existing Data

x = [1,2,3]

a = np.asarray(x)

list = range(5)

it = iter(list) #iter function returns iterator

x = np.fromiter(it, dtype = float)

print (x)


[0. 1. 2. 3. 4.]


In [17]:
#Extraction by Slicing.

for x in np.nditer(a):
    print (x)

a = np.arange(10)

s = slice(2,7,2) # slice (start ,stop , step)

print (a[s])

b = a[2:7:2]

print (b)

a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print (a)

print ('The items in the second column are:')

print (a[...,1])

print ('The items in the second row are:')

print (a[1,...])

1
2
3
[2 4 6]
[2 4 6]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
The items in the second column are:
[2 4 5]
The items in the second row are:
[3 4 5]


In [18]:
# Now we will slice all items from column 1 onwards

print ('The items column 1 onwards are:')

print (a[...,1:])

a = np.array([0,30,45,60,90])

print ('Array containing sine values:')

sin = np.sin(a*np.pi/180)

print (sin)

print ('\n')

print ('Compute sine inverse of angles. Returned values are in radians.')

inv = np.arcsin(sin)

print (inv)

print ('\n')

print ('Check result by converting to degrees:')

print (np.degrees(inv))

print ('\n')

print ('arccos and arctan functions behave similarly:')

cos = np.cos(a*np.pi/180)

print (cos)

print ()

print ('Inverse of cos:')

inv = np.arccos(cos)

print (inv)

print ('\n')

print ('Tan function:')

tan = np.tan(a*np.pi/180)

print (tan)

print ('Inverse of tan:')

inv = np.arctan(tan)

print (inv)

print ('In degrees:')

print (np.degrees(inv))

The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
Array containing sine values:
[0.         0.5        0.70710678 0.8660254  1.        ]


Compute sine inverse of angles. Returned values are in radians.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Check result by converting to degrees:
[ 0. 30. 45. 60. 90.]


arccos and arctan functions behave similarly:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Inverse of cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Tan function:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
Inverse of tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
In degrees:
[ 0. 30. 45. 60. 90.]


In [16]:
arr=np.array([[1,4,9],[16,169,49],[4,36,25]])
print(arr)
arr_sq=np.sqrt(arr)
print(arr_sq)


[[  1   4   9]
 [ 16 169  49]
 [  4  36  25]]
[[ 1.  2.  3.]
 [ 4. 13.  7.]
 [ 2.  6.  5.]]


In [19]:
flat=arr.flatten()
print(flat)


[  1   4   9  16 169  49   4  36  25]


In [24]:
arr_ravel=arr.ravel()
print(arr_ravel)
arr_ravel.shape=[3,3]
print(arr_ravel)


[  1   4   9  16 169  49   4  36  25]
[[  1   4   9]
 [ 16 169  49]
 [  4  36  25]]


In [ ]:
#Find the Eiganvalues and Eiganvectors
#8009387408


The following command must be run outside of the IPython shell:

    $ pip install opencv-python

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/
