In [1]:
import cv2 as cv
from matplotlib import pyplot as plt
import numpy as np



In [2]:
img = cv.imread(r'/home/udit/Downloads/BabyBaboon.jpeg',1)
print(type(img))

print(img)
print(img.shape)
px = img[10,100]
print(px)

cv.imshow('Image',img)
cv.waitKey()
cv.destroyAllWindows()

<class 'numpy.ndarray'>
[[[ 46  76  51]
  [ 46  76  51]
  [ 46  76  51]
  ...
  [  1 118  63]
  [  0 118  63]
  [  0 118  63]]

 [[ 46  76  51]
  [ 46  76  51]
  [ 46  76  51]
  ...
  [  1 118  63]
  [  0 118  63]
  [  0 119  64]]

 [[ 46  76  51]
  [ 46  76  51]
  [ 46  76  51]
  ...
  [  0 119  64]
  [  0 119  64]
  [  0 119  64]]

 ...

 [[  2   4   5]
  [  1   3   4]
  [  1   2   6]
  ...
  [  0   3   4]
  [  0   1   2]
  [  0   0   1]]

 [[  4   3   7]
  [  4   3   7]
  [  3   2   6]
  ...
  [  0   2   3]
  [  0   1   2]
  [  0   0   1]]

 [[  4   3   7]
  [  4   3   7]
  [  3   2   6]
  ...
  [  1   3   4]
  [  2   1   3]
  [  2   1   3]]]
(424, 640, 3)
[80 95 97]


In [2]:
# 1.Output an updated image without green channel
# 2.Find the invented image of the original image (don't use direct function use 100ps)
# hint: Substract individual pixels in each channel with 255

img = cv.imread(r'/home/udit/Downloads/BabyBaboon.jpeg',1)
cv.imshow("Pic",img)
img_not = cv.bitwise_not(img)
cv.imshow("Invert1",img_not)
cv.waitKey(0)
cv.destroyAllWindows()

In [3]:

src = cv.imread('/home/udit/Downloads/BabyBaboon.jpeg', cv.IMREAD_UNCHANGED)
print(src.shape)

src[:,:,1] = np.zeros([src.shape[0], src.shape[1]])

cv.imwrite('/home/udit/Semester6/TTL/LAB6_MAR02/nogreenBabyBaboon.jpeg',src)


(424, 640, 3)


True